# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        exclude: ^(npins/.*)$
      - id: end-of-file-fixer
        exclude: ^(npins/.*)$
      - id: check-yaml
        exclude: ^(packages/backend/aws-sam.template.yml)$
      - id: check-added-large-files
      - id: detect-private-key
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: shellcheck
        name: check shell scripts
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.30.0
    hooks:
      - id: check-jsonschema
        entry: check-jsonschema
        name: check-secret-config-jsonschema
        files: 'secret/config.json'
        args:
          - --schemafile
          - config.schema.json
          - --verbose
